<?php
/**
 * @file
 * This is an example module to illustrate all the power and magic
 * available from the Drupal menu system.
 */

/**
 * Implements hook_menu().
 */
function menu_magic_menu() {
  $items = array();

  /**
   * This chunk of code defines a new menu item at the path 'magic'. When a user 
   * with the 'access content' permission visits it, our menu_magic_basic
   * function will be called to build the page's content.
   */
  $items['magic'] = array(
    'title' => 'A little magic',
    'page callback' => 'menu_magic_basic',
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
    'file' => 'menu_magic.basic.inc', // Drupal will auto-include this file
    'type' => MENU_NORMAL_ITEM,
  );

  /**
   * This one defines a menu item beneath 'magic' that requires an additional
   * argument in the URL. 'magic/1', 'magic/fred', and so on are all valid.
   * The 'wildcard' value will be passed to the page callback, and the callback
   * is responsible for doing something with it. 
   */
  $items['magic/%'] = array(
    'title' => 'Even more magical!',
    'page callback' => 'menu_magic_extra',
    'page arguments' => array(1),
    'access callback' => 'menu_magic_page_access',
    'file' => 'menu_magic.extra.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  /**
   * The User module already defines a page at the path 'user/%', and this
   * chunk of code defines an additional page just underneath it. Because
   * the type of this ite is MENU_LOCAL_TASK, it appears as a tab on the user
   * profile page rather than a standalone menu item.
   */
  $items['user/%/magic'] = array(
    'title' => 'Magic',
    'description' => 'Magical magic for users',
    'page callback' => 'menu_magic_user_tab',
    'page arguments' => array(1),
    'access callback' => 'user_access',
    'access arguments' => array('administer users'),
    'file' => 'menu_magic.user.inc',
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

function menu_magic_page_access() {
  return TRUE;
}