<?php
/**
 * @file
 * This is an example module to illustrate all the power and magic
 * available from the Drupal menu system.
 */

/**
 * Implements hook_menu().
 */
function menu_magic_menu() {
  $items = array();

  /**
   * This chunk of code defines a new menu item at the path 'magic'. When a user 
   * with the 'access content' permission visits it, our menu_magic_basic
   * function will be called to build the page's content.
   */
  $items['magic'] = array(
    'title' => 'A little magic',
    'page callback' => 'menu_magic_basic',
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
    'file' => 'menu_magic.basic.inc', // Drupal will auto-include this file
    'type' => MENU_NORMAL_ITEM,
  );

  /**
   * This one defines a menu item beneath 'magic' that requires an additional
   * argument in the URL. 'magic/1', 'magic/fred', and so on are all valid.
   * The 'wildcard' value will be passed to the page callback, and the callback
   * is responsible for doing something with it. 
   */
  $items['magic/%'] = array(
    'title' => 'Even more magical!',
    'page callback' => 'menu_magic_extra',
    'page arguments' => array(1),
    'access callback' => 'menu_magic_page_access',
    'file' => 'menu_magic.extra.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  /**
   * The User module already defines a page at the path 'user/%', and this
   * chunk of code defines an additional page just underneath it. Because
   * the type of this ite is MENU_LOCAL_TASK, it appears as a tab on the user
   * profile page rather than a standalone menu item.
   */
  $items['user/%/magic'] = array(
    'title' => 'Magic',
    'description' => 'Magical magic for users',
    'page callback' => 'menu_magic_user_tab',
    'page arguments' => array(1),
    'access callback' => 'user_access',
    'access arguments' => array('administer users'),
    'file' => 'menu_magic.user.inc',
    'type' => MENU_LOCAL_TASK,
  );


  /**
   * This one defines a Local Task much like the "node edit" link.
   * It's a normal menu item, but it uses the 'context' setting to move its link
   * to the Contextual Links dropdown that appears next to each node.
   * 
   * In addition, it uses a named wildcard in its path -- %node. Like the generic
   * '%' wildcard, it allows many values, but Drupal will automatically verify
   * that the value is a node id, load the full node, and pass it on to the
   * page callback.
   */
  $items['node/%node/magic'] = array(
    'title' => 'Magic',
    'description' => 'Do amazing and magical things',
    'page callback' => 'menu_magic_node_context',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'file' => 'menu_magic.context.inc',
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_INLINE,
  );


  return $items;
}



/**
 * This is a menu access callback; it can accept parameters from the menu items
 * that call it, and determine if the current user should be allowed to see the
 * page in question. This one always returns TRUE: it's not very discriminating.
 */
function menu_magic_page_access() {
  return TRUE;
}


/**
 * This hook tells Drupal what URL paths should use the Administration theme and
 * the 'Overlay' popup window.
 */
function menu_magic_admin_paths() {
  return array(
    'node/*/magic' => TRUE,
  );
}